# Site settings
title: JTechLog
lead: Viczián István magyar nyelvű Java blogja
description: Viczián István magyar nyelvű Java blogja
url: "http://www.jtechlog.hu"
author: Viczián István
twitter_username: vicziani
github_username: vicziani
exclude: [README.md]

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

kramdown:
  input: GFM
  hard_wrap: false